### ISSUE TITLE
Make numpy install requirements strict

### ISSUE THREAD

**Issue by dmitryshribak** [EfficientTraining/LabelBench#50]
With numpy 2.0, I get: AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.

**Comment by jifanz** [comment]
Thanks for raising this issue. Could you please let us know where the error was reported? A better solution would be for us to modify the code so it’s version compatible.

**Comment by dmitryshribak** [comment]
I ran the following command:


python main.py --seed 1234 --wandb_name $WANDB_NAME --dataset cifar10 --data_dir ./data --metric multi_class --batch_size 1000 --num_batch 10 --embed_model_config none.json --classifier_model_config clip_ViTB32_pretrained.json --strategy_config random_sampling.json --trainer_config cifar10/passive/clip_ViTB32_finetune.json --corrupter_config noiseless.json

**Comment by jifanz** [comment]
Thanks, it should be fixed now.
